# Generated by Django 3.2.7 on 2021-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
    ]
