# Generated by Django 3.2.7 on 2021-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Description',
            field=models.TextField(max_length=2000),
        ),
    ]
