# Generated by Django 3.2.7 on 2021-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0002_alter_staff_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.PositiveIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
