# Generated by Django 3.2.7 on 2021-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0003_auto_20210909_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='GatedGuarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='HighRise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
