# Generated by Django 3.2.7 on 2021-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0004_complex_gatedguarded_highrise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatedguarded',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
