# Generated by Django 3.2.7 on 2021-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0005_alter_gatedguarded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='highrise',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
