# Generated by Django 3.2.7 on 2021-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0006_auto_20210909_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
