# Generated by Django 3.2.7 on 2021-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0009_alter_ourservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
